make it possible to configure a path to either round edges or not
daleblackwood/goshapes pull request #19
Opened 2024-08-24 07:07 UTC by GGAlanSmithee

fixes #18 by adding the option to either round edges, or not.

see #18 for context, and the video below for results. 

_IMO having `set_edges=false` as a default makes more sense (at least for `*WallShaper`s) but that would be a breaking change, so I set the default to `true`._

 

https://github.com/user-attachments/assets/1b4e21ec-3cdf-4d47-8176-e5baeb5e4660

2024-08-24 07:59 UTC, GGAlanSmithee commented
Just as in #20 this requires you to update the screenshot of the `PathOptions` editor block in the `README.md`, as I cannot upload it to your account. (I could add the images to the repo, but that's not what you've done previously, so don't want to divert)

2024-08-29 16:14 UTC, daleblackwood commented
Thanks for your input! I've just been released on 1.2.0 but I'm close to this project at the moment and will evaluate your PRs for 1.2.1 in the coming weeks.

2024-08-30 08:34 UTC, daleblackwood commented
Thanks for the contribution. Is this different from setting rounding to 0?

2024-08-30 08:35 UTC, daleblackwood requested changes
Just seeking clarification on feature's functionality / whether it's doubling up.

2024-08-30 11:04 UTC, GGAlanSmithee commented
@daleblackwood feel free to question and ask about anything :)

This is different from setting `rounding=0` since this only affects the first and the last point in the path, which allows for the usecase displayed in the video, which is to have a path that

1. is rounded (`rounding > 0`), as it twists and turns (ie, no sharp corners), while at the same time
1. not have the edges of the path turn towards each other, which is otherwise the case when using `rounding > 0`

2024-09-03 12:12 UTC, closed without merging

2024-09-03 15:50 UTC, GGAlanSmithee commented
@daleblackwood I see this was closed, is that because `v1.2` was closed, or because you do not intend to merge this? I do think there is some merit to this, since without this (or something like it) some shapes are quite hard to model. I will rebase this and open a PR toward #41 in case you _do_ want it.