Feature/add round edges option
daleblackwood/goshapes pull request #42
Opened 2024-09-03 15:56 UTC by GGAlanSmithee

_copied from #19, rebased_

fixes #18 by adding the option to either round edges, or not.

see #18 for context, and the video below for results. 

_IMO having `set_edges=false` as a default makes more sense (at least for `*WallShaper`s) but that would be a breaking change, so I set the default to `true`._

 

https://github.com/user-attachments/assets/1b4e21ec-3cdf-4d47-8176-e5baeb5e4660

2024-09-04 13:47 UTC, daleblackwood commented
Thanks for this, I really like the idea - I'm wondering if your previous option for turning turning rounding off and this could be rolled into one with a round_mode enum.

Something like:
```
enum RoundingMode { Auto, Edges, Off }
var rounding_mode := RoundingMode.Auto
```

2024-09-04 13:48 UTC, daleblackwood requested changes

2024-09-04 13:48 UTC, daleblackwood commented on addons/goshapes/base/PathOptions.gd
> +@export var round_edges: bool = true:
consider enum
```
enum RoundingMode { Auto, Ignore_Edges, Off }
var rounding_mode
```

2024-09-04 17:39 UTC, GGAlanSmithee commented
the `enum` solution is much better - I will update the PR.

2024-09-04 18:17 UTC, GGAlanSmithee commented
I made the requested change. I used a "local enum" (not too familiar with GDScript enums) which makes them quite verbose (`PathOptions.RoundingMode.Ignore_Edges`), let me know if you prefer a global enum instead @daleblackwood

2024-09-05 07:51 UTC, daleblackwood approved these changes

2024-09-05 07:51 UTC, merged